### ISSUE TITLE
[Bug] When at least one of the values ​​in the tags is blank, the blog page cannot be opened

### ISSUE THREAD

**Issue by IAMIBM** [TuiMao233/valaxy-theme-hairy#4]
**valaxy-theme-hairy: v1.2.4**

When at least one of the values ​​in the tags is blank, the blog page cannot be opened.

For example, in front matter, delete "111" or "222" or both, blog page can not be opened.

---
title: test
date: 2024-08-26
updated: 2024-08-26
categories: Tim
tags:
- 111
- 222
---

**Comment by hairyf** [comment]
I used the following configuration and did not encounter the issue you mentioned.

```md
---
title: test
date: 2024-08-26
updated: 2024-08-26
categories: Tim
tags:
- 
- 222
---
```
